"""
fig_plate_cooling_joint.py

Two-panel figure showing the half-space cooling predictions for the oceanic
lithosphere: surface heat flow (left) and seafloor depth below ridge crest
(right), both as functions of seafloor age (0–100 Ma).

Physics follows Turcotte & Schubert (2014), Geodynamics 3rd ed., §4.2–4.4.
Numerical constants: Tm = 1300 °C, Ts = 0 °C, kappa = 1e-6 m^2/s,
k = 3.3 W/m/K, rho_m = 3300, rho_w = 1000 kg/m^3, alpha = 3e-5 1/K,
d_r = 2500 m.

Synthetic observations are generated by adding Gaussian noise to the
half-space predictions (young seafloor only for depth, to show the
plate-model flattening of old seafloor).

Output: assets/figures/fig_plate_cooling_joint.png
License: CC-BY 4.0
"""
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl

mpl.rcParams.update({
    "font.size": 12,
    "axes.labelsize": 13,
    "xtick.labelsize": 11,
    "ytick.labelsize": 11,
    "legend.fontsize": 10,
    "figure.dpi": 150,
    "savefig.dpi": 300,
})

# ── Physical constants ──────────────────────────────────────────────────
Tm      = 1300.0       # mantle temperature, °C
Ts      = 0.0          # surface temperature, °C
kappa   = 1.0e-6       # thermal diffusivity, m²/s
k       = 3.3          # thermal conductivity, W/m/K
rho_m   = 3300.0       # mantle density, kg/m³
rho_w   = 1000.0       # seawater density, kg/m³
alpha   = 3.0e-5       # thermal expansivity, K⁻¹
d_r     = 2500.0       # ridge-crest depth, m

SEC_MY  = 1.0e6 * 365.25 * 24 * 3600   # s / Myr

# ── Age axis ────────────────────────────────────────────────────────────
t_max   = 100.0        # Myr
t_ma    = np.linspace(0.5, t_max, 500)   # Myr (avoid t=0 singularity)
t_s     = t_ma * SEC_MY                  # seconds

# ── Half-space predictions ───────────────────────────────────────────────
q_pred  = k * (Tm - Ts) / np.sqrt(np.pi * kappa * t_s) * 1e3   # mW/m²
d_pred  = d_r + (2 * rho_m * alpha * (Tm - Ts)) / (rho_m - rho_w) \
          * np.sqrt(kappa * t_s / np.pi)                           # m

# ── Synthetic observations ───────────────────────────────────────────────
rng     = np.random.default_rng(42)

# Heat flow: scatter ~8% around half-space, all ages
t_obs_q = np.array([2, 5, 10, 15, 25, 35, 50, 70, 90])
q_obs_t = k * (Tm - Ts) / np.sqrt(np.pi * kappa * t_obs_q * SEC_MY) * 1e3
q_obs   = q_obs_t * (1 + rng.normal(0, 0.08, len(t_obs_q)))
q_obs   = np.clip(q_obs, 1, None)

# Depth: follow half-space for young (<= 60 Ma), then flatten for old
t_obs_d = np.array([3, 8, 15, 25, 40, 55, 65, 75, 90, 100])
d_obs_t = d_r + (2 * rho_m * alpha * (Tm - Ts)) / (rho_m - rho_w) \
          * np.sqrt(kappa * t_obs_d * SEC_MY / np.pi)
noise_d = rng.normal(0, 120, len(t_obs_d))
d_obs   = d_obs_t + noise_d
# Flatten old seafloor (simulate plate model; cap depth ~5900 m)
plateau_d = 5900.0
old_mask  = t_obs_d > 60
d_obs[old_mask] = plateau_d - rng.uniform(-200, 200, old_mask.sum())

# ── Plot ─────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 5), sharey=False)

# Left: heat flow
ax = axes[0]
ax.plot(t_ma, q_pred, color="#D55E00", lw=2.2, label="Half-space model")
ax.scatter(t_obs_q, q_obs, s=45, color="#0072B2", zorder=5,
           label="Synthetic observations")
ax.set_xlabel("Seafloor age (Ma)")
ax.set_ylabel("Surface heat flow  (mW m$^{-2}$)")
ax.set_xlim(0, t_max)
ax.set_ylim(0, 320)
ax.set_title("Heat flow  $q \\propto t^{-1/2}$", fontsize=13)
ax.annotate("hot, thin\nlithosphere\nnear ridge",
            xy=(5, 230), xytext=(18, 280),
            fontsize=9, color="#555555",
            arrowprops=dict(arrowstyle="->", color="#555555", lw=1.0))
ax.legend(loc="upper right", framealpha=0.85)
ax.spines[["top", "right"]].set_visible(False)

# Right: depth (positive downward)
ax = axes[1]
ax.plot(t_ma, d_pred / 1000, color="#D55E00", lw=2.2, label="Half-space model")
ax.scatter(t_obs_d, d_obs / 1000, s=45, marker="s", color="#0072B2", zorder=5,
           label="Synthetic observations")
ax.set_xlabel("Seafloor age (Ma)")
ax.set_ylabel("Depth below ridge crest  (km)")
ax.set_xlim(0, t_max)
ax.invert_yaxis()
ax.set_title("Seafloor depth  $d \\propto t^{+1/2}$", fontsize=13)
ax.annotate("old seafloor flattens\n(plate model needed)",
            xy=(80, 5.9), xytext=(50, 5.0),
            fontsize=9, color="#555555",
            arrowprops=dict(arrowstyle="->", color="#555555", lw=1.0))
ax.legend(loc="lower right", framealpha=0.85)
ax.spines[["top", "right"]].set_visible(False)

fig.tight_layout()
out = "assets/figures/fig_plate_cooling_joint.png"
fig.savefig(out, bbox_inches="tight")
print(f"Saved: {out}")
