"""
fig_l30_group1_networks.py

Scientific content: two complementary observing-network designs for constraining
Earth's deep interior, the design task for Group 1.

  Design A - satellite-led: a constellation in orbit senses Earth's GLOBAL
  fields - the gravity field and its monthly mass changes (e.g. GRACE-FO
  inter-satellite ranging), the magnetic field generated by the outer-core
  geodynamo (e.g. Swarm), and Earth's rotation, precession and nutation (space
  geodesy) which fix the moment of inertia. These give bulk, integrated
  properties (core size, mean density, core dynamics) with excellent global
  coverage but weak vertical resolution.

  Design B - ground-led: a global network of seismometers records elastic waves
  from earthquakes - body-wave travel times and the PKP shadow, plus the
  planet's free oscillations (normal modes). These pin SHARP radial structure
  (the depths of the core-mantle and inner-core boundaries, velocity jumps, and
  whether a layer is solid or liquid) but need earthquakes and suffer uneven
  station coverage, especially over oceans.

Together they reduce the null space: satellites fix the global mass and field
budget; ground sensors fix the sharp boundaries and state.

Schematic design diagram (original code). Sensor concepts after GRACE-FO,
Swarm, and the Global Seismographic Network.

Output: assets/figures/fig_l30_group1_networks.png
License: CC-BY 4.0 (this script)
"""
import os
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.patches import Circle, FancyArrowPatch
from scipy.integrate import solve_ivp

mpl.rcParams.update({
    "font.size": 13,
    "axes.titlesize": 15,
    "axes.labelsize": 13,
    "xtick.labelsize": 12,
    "ytick.labelsize": 12,
    "legend.fontsize": 11,
    "figure.dpi": 150,
    "savefig.dpi": 300,
})

COLORS = ["#0072B2", "#E69F00", "#56B4E9", "#009E73",
          "#D55E00", "#CC79A7", "#000000"]
FIGDIR = os.path.join(os.path.dirname(__file__), "..", "figures")

# --- PREM-like model for ray tracing (Design B). The unit-radius cartoon uses
#     Earth's true core fractions (0.55, 0.19), so traced rays in km map onto it
#     by dividing by R_E. Velocity RISES with depth in the mantle, so rays curve
#     concave toward the surface and turn; it DROPS at the CMB, refracting P into
#     the core as PKP. ---
R_E = 6371.0
R_CMB = 3480.0
R_ICB = 1220.0
_W = 40.0


def vp(r):
    f = np.clip((R_E - r) / (R_E - R_CMB), 0, 1)
    vm = 8.0 + (13.7 - 8.0) * f ** 0.55                          # mantle
    voc = 8.0 + (10.3 - 8.0) * ((R_CMB - r) / (R_CMB - R_ICB))   # outer core
    s_cmb = 0.5 * (1 + np.tanh((r - R_CMB) / _W))
    s_icb = 0.5 * (1 + np.tanh((r - R_ICB) / _W))
    return s_cmb * vm + (1 - s_cmb) * (s_icb * voc + (1 - s_icb) * 11.0)


def trace(a_deg, stop_core, smax=45000):
    """Kinematic spherical ray (p = r sin i / v conserved), source at the top."""
    def deriv(s, Y):
        x, y, px, py = Y
        r = np.hypot(x, y)
        vv = vp(r)
        dvdr = (vp(r + 1.0) - vp(r - 1.0)) / 2.0
        g = -dvdr / (vv * vv * r)
        return [vv * px, vv * py, g * x, g * y]
    a = np.radians(a_deg)
    u0 = 1.0 / vp(R_E)
    Y0 = [0.0, R_E, np.sin(a) * u0, -np.cos(a) * u0]

    def surf(s, Y):
        return np.hypot(Y[0], Y[1]) - R_E
    surf.terminal = True
    surf.direction = +1
    events = [surf]
    if stop_core:
        def core(s, Y):
            return np.hypot(Y[0], Y[1]) - R_CMB
        core.terminal = True
        core.direction = -1
        events.append(core)
    sol = solve_ivp(deriv, [0, smax], Y0, events=events, max_step=8,
                    rtol=1e-9, atol=1e-7)
    return sol.y[0] / R_E, sol.y[1] / R_E


def draw_earth(ax):
    ax.add_patch(Circle((0, 0), 1.0, facecolor="#EAF2F8", edgecolor=COLORS[6],
                        lw=1.4, zorder=1))
    ax.add_patch(Circle((0, 0), 0.55, facecolor="#FBE3C8", edgecolor=COLORS[6],
                        lw=1.0, zorder=2))
    ax.add_patch(Circle((0, 0), 0.19, facecolor="#F1C27A", edgecolor=COLORS[6],
                        lw=0.8, zorder=3))


def polar(r, deg):
    t = np.radians(deg)
    return r * np.sin(t), r * np.cos(t)


def main():
    fig, (axA, axB) = plt.subplots(1, 2, figsize=(13.0, 7.2))

    # =================== Design A: satellite-led ===================
    draw_earth(axA)
    axA.text(0, 0.0, "core", ha="center", va="center", fontsize=9)
    orb = 1.42
    th = np.linspace(0, 360, 200)
    axA.plot(orb * np.sin(np.radians(th)), orb * np.cos(np.radians(th)),
             ls=(0, (4, 3)), color=COLORS[6], lw=0.9, zorder=4)

    # GRACE-FO pair
    g1 = polar(orb, 52); g2 = polar(orb, 64)
    axA.plot(*zip(g1, g2), color=COLORS[0], lw=1.4, zorder=5)
    for g in (g1, g2):
        axA.plot(*g, marker="s", ms=11, color=COLORS[0], zorder=6)
    axA.annotate("GRACE-FO pair\ninter-satellite range\n-> gravity & monthly mass",
                 (g2[0], g2[1]), (1.55, 1.15), fontsize=9.5, ha="left",
                 color=COLORS[0])
    for g in (g1, g2):
        axA.add_patch(FancyArrowPatch(g, (g[0] * 0.55, g[1] * 0.55),
                      arrowstyle="-|>", mutation_scale=10, color=COLORS[0],
                      lw=0.8, ls=":", zorder=4))

    # magnetic survey satellite (Swarm)
    m = polar(orb, 200)
    axA.plot(*m, marker="s", ms=11, color=COLORS[4], zorder=6)
    axA.add_patch(FancyArrowPatch(m, (m[0] * 0.45, m[1] * 0.45),
                  arrowstyle="-|>", mutation_scale=12, color=COLORS[4], lw=1.4,
                  zorder=5))
    axA.annotate("magnetic survey\n(Swarm)\n-> geodynamo in\nthe outer core",
                 m, (-2.05, -0.2), fontsize=9.5, ha="left", color=COLORS[4])

    # precession / rotation
    axA.add_patch(FancyArrowPatch((0.32, 1.18), (-0.32, 1.18),
                  arrowstyle="-|>", mutation_scale=12,
                  connectionstyle="arc3,rad=0.5", color=COLORS[5], lw=1.6))
    axA.text(0, 1.5, "rotation / precession\n-> moment of inertia",
             ha="center", fontsize=9.5, color=COLORS[5])

    axA.text(0, -1.78,
             "Senses GLOBAL fields: gravity + mass change, magnetic (geodynamo),\n"
             "rotation. Bulk core size & density, core dynamics.\n"
             "Strength: global coverage.  Limit: weak vertical resolution.",
             ha="center", va="top", fontsize=9.8,
             bbox=dict(boxstyle="round,pad=0.4", fc="#EAF4FB", ec=COLORS[0]))
    axA.set_title("Design A - satellite-led", fontsize=15, color=COLORS[0])
    axA.set_xlim(-2.1, 2.1); axA.set_ylim(-2.3, 1.9)
    axA.set_aspect("equal"); axA.axis("off")

    # =================== Design B: ground-led ===================
    draw_earth(axB)
    axB.text(0, 0.0, "core", ha="center", va="center", fontsize=9)

    # ground stations around the rim
    for deg in range(0, 360, 24):
        sx, sy = polar(1.0, deg)
        ang = np.radians(deg)
        axB.plot(sx, sy, marker="^", ms=9, color=COLORS[3],
                 markeredgecolor=COLORS[6], markeredgewidth=0.5, zorder=6)

    # earthquake source + ray-traced body waves. Velocity rises with depth, so
    # the rays curve concave toward the surface and turn in the mantle; the
    # steep ray refracts through the low-velocity outer core as PKP.
    axB.plot(0, 1.0, marker="*", ms=18, color=COLORS[6], zorder=7)
    for a in (40, 26):                       # direct P/S, turn in the mantle
        rx, ry = trace(a, stop_core=True)
        axB.plot(rx, ry, color=COLORS[0], lw=1.8, zorder=5)
    rx, ry = trace(7, stop_core=False)       # PKP, refracts through the core
    axB.plot(rx, ry, color=COLORS[4], lw=1.8, zorder=5)
    axB.text(0.9, 0.5, "body waves\n(P, S, PKP)\n-> travel times,\nshadow zone",
             fontsize=9.5, ha="left", color=COLORS[0])

    # free oscillations (normal modes) - a dashed deformed ring
    phi = np.radians(th)
    rr2 = 1.12 + 0.06 * np.cos(2 * phi)
    axB.plot(rr2 * np.sin(phi), rr2 * np.cos(phi), ls=(0, (2, 2)),
             color=COLORS[5], lw=1.2, zorder=4)
    axB.text(-1.15, 1.35, "free oscillations\n(normal modes)\n-> whole-Earth\nstructure",
             fontsize=9.5, ha="left", color=COLORS[5])

    axB.text(0, -1.78,
             "Senses ELASTIC waves: body-wave travel times (PKP shadow) and\n"
             "normal modes. Sharp boundaries (CMB, ICB), velocity jumps, state.\n"
             "Strength: sharp radial resolution.  Limit: needs quakes; sparse oceans.",
             ha="center", va="top", fontsize=9.8,
             bbox=dict(boxstyle="round,pad=0.4", fc="#FBEFE3", ec=COLORS[4]))
    axB.set_title("Design B - ground-led", fontsize=15, color=COLORS[4])
    axB.set_xlim(-2.1, 2.1); axB.set_ylim(-2.3, 1.9)
    axB.set_aspect("equal"); axB.axis("off")

    fig.suptitle("Group 1 extension - two network designs for Earth's deep interior",
                 fontsize=16, y=0.99)
    fig.text(0.5, 0.045,
             "Joint move: satellites fix the global mass and field budget; ground sensors fix the sharp boundaries and state. "
             "Together they pin core radius, density, and liquid/solid state.",
             ha="center", fontsize=10.5, style="italic")
    fig.tight_layout(rect=[0, 0.06, 1, 0.96])
    out = os.path.join(FIGDIR, "fig_l30_group1_networks.png")
    fig.savefig(out, dpi=300, bbox_inches="tight")
    print("wrote", out)


if __name__ == "__main__":
    main()
